services:
  db:
    image: mysql:9.4.0
    container_name: connected-db-local
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: connected
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_pw}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${DB_ROOT_PASSWORD:-root_pw} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:8.2.2
    container_name: connected-redis-local
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data: