services:
  db:
    image: mysql:8.0
    container_name: connected_db
    environment:
      MYSQL_DATABASE: connected
      MYSQL_USER: connected
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_pw}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${DB_ROOT_PASSWORD:-root_pw} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build:
      context: .
    image: connected-api:dev
    container_name: connected_app
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      CANVAS_URI: ${CANVAS_URI}
      CANVAS_CLIENT_ID: ${CANVAS_CLIENT_ID}
      CANVAS_CLIENT_SECRET: ${CANVAS_CLIENT_SECRET}
      FRONTEND_URI: ${FRONTEND_URI}
      BACKEND_URL: ${BACKEND_URL}

      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_PROTOCOL: ${MAIL_PROTOCOL}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  db_data:
