services:
  db:
    image: mysql:9.4.0
    container_name: connected_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: connected
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: