connected:
  canvas-uri: ${CANVAS_URI}
  frontend-uri: ${FRONTEND_URI}

spring:
  application:
    name: connected

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # optional; Hibernate 6 can auto-detect

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: ${MAIL_PROTOCOL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000

  security:
    oauth2:
      client:
        registration:
          canvas:
            client-id: ${CANVAS_CLIENT_ID}
            client-secret: ${CANVAS_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: "${BACKEND_URL}/login/oauth2/code/canvas"
            authorization-grant-type: authorization_code
            scope:
              - "url:GET|/api/v1/users/:id"
              - "url:GET|/api/v1/courses"
              - "url:GET|/api/v1/courses/:course_id/assignments"
              - "url:GET|/api/v1/courses/:course_id/enrollments"
            client-name: Canvas
        provider:
          canvas:
            user-name-attribute: id
            authorization-uri: ${connected.canvas-uri}/login/oauth2/auth
            token-uri: ${connected.canvas-uri}/login/oauth2/token
            user-info-uri: ${connected.canvas-uri}/api/v1/users/self
