spring:
  application:
    name: connected
  datasource:
    url: jdbc:mysql://localhost:3306/connected
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          canvas:
            client-id: 10000000000001
            client-secret: 8cwXkT7h3TvLaHEcfZ88twkEUYATyCZBFnVWPmnVXtf4XDTAC33TvL8W8Zn9F2at
            client-authentication-method: client_secret_post
            redirect-uri: '{baseUrl}/login/oauth2/code/canvas'
            authorization-grant-type: authorization_code
            scope: email, offline_access
            client-name: Canvas
        provider:
          canvas:
            user-name-attribute: email
            authorization-uri: https://canvas.mertenshome.com/login/oauth2/auth
            token-uri: https://canvas.mertenshome.com/login/oauth2/token
            user-info-uri: https://canvas.mertenshome.com/api/v1/users/self


#Trace logging
#logging:
#  level:
#    org.springframework.web: TRACE
#    org.springframework.security: TRACE
#    org.springframework.security.oauth2: TRACE
#    org.springframework.security.oauth2.client: TRACE
#    org.springframework.security.oauth2.client.web: TRACE
#    org.springframework.security.oauth2.client.endpoint: TRACE
#    org.springframework.security.oauth2.client.authentication: TRACE
#    org.springframework.security.oauth2.client.registration: TRACE
#    org.springframework.security.oauth2.client.registration.ClientRegistration: TRACE
#    org.springframework.security.oauth2.client.registration.ClientRegistrationRepository: TRACE
