custom:
  admin-token: ${ADMIN_TOKEN}
  canvas-api-uri: https://canvas.mertenshome.com
  frontend-uri: http://localhost:4200

spring:
  application:
    name: connected
  datasource:
    url: jdbc:mysql://localhost:3306/connected
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          canvas:
            client-id: ${CANVAS_CLIENT_ID}
            client-secret: ${CANVAS_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: '{baseUrl}/login/oauth2/code/canvas'
            authorization-grant-type: authorization_code
            scope: offline_access
            client-name: Canvas
        provider:
          canvas:
            user-name-attribute: email
            authorization-uri: ${custom.canvas-api-uri}/login/oauth2/auth
            token-uri: ${custom.canvas-api-uri}/login/oauth2/token
            user-info-uri: ${custom.canvas-api-uri}/api/v1/users/self?include[]=email